// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_pages_layout from "./routes/(pages)/_layout.tsx";
import * as $_pages_beforeafter from "./routes/(pages)/beforeafter.tsx";
import * as $_pages_clicktochange from "./routes/(pages)/clicktochange.tsx";
import * as $_pages_data from "./routes/(pages)/data.tsx";
import * as $_pages_dropdowngraph from "./routes/(pages)/dropdowngraph.tsx";
import * as $_pages_index from "./routes/(pages)/index.tsx";
import * as $AfterGraph from "./islands/AfterGraph.tsx";
import * as $FilterBar from "./islands/FilterBar.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $SmallGraph from "./islands/SmallGraph.tsx";
import * as $TableData from "./islands/TableData.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(pages)/_layout.tsx": $_pages_layout,
    "./routes/(pages)/beforeafter.tsx": $_pages_beforeafter,
    "./routes/(pages)/clicktochange.tsx": $_pages_clicktochange,
    "./routes/(pages)/data.tsx": $_pages_data,
    "./routes/(pages)/dropdowngraph.tsx": $_pages_dropdowngraph,
    "./routes/(pages)/index.tsx": $_pages_index,
  },
  islands: {
    "./islands/AfterGraph.tsx": $AfterGraph,
    "./islands/FilterBar.tsx": $FilterBar,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/SmallGraph.tsx": $SmallGraph,
    "./islands/TableData.tsx": $TableData,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
